"""SQLAlchemy ORM model for deterministic investment scores."""

import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, Text, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func
from sqlalchemy import Float

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.document import Document

from sqlalchemy.dialects.postgresql import JSONB


class AssessmentStatus(str, enum.Enum):
    """Whether enough evidence exists to responsibly present a single
    overall investment score (Evidence Layer plan, Step 8).

    Before this, `overall_score` could look confident (e.g. "75/100")
    even when only one of four scoring dimensions had any data at all —
    missing dimensions were silently dropped from the weighted average's
    denominator, which hides the gap rather than surfacing it.

    Attributes:
        SUFFICIENT_EVIDENCE: `overall_score` is a real weighted
            composite, per `investment_scoring_service.py`'s fixed
            thresholds (coverage, confidence, and dimension-count all
            being adequate).
        INSUFFICIENT_EVIDENCE: `overall_score` is `None` — not a
            lowered number, an absent one. The per-category sub-scores
            (`financial_score`, etc.) are still populated wherever they
            individually have data; only the single composite number is
            withheld, since presenting one would overclaim precision
            the evidence doesn't support.
    """

    SUFFICIENT_EVIDENCE = "sufficient_evidence"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"


class InvestmentScore(Base):
    """Deterministic investment score derived from a document's existing
    financial metrics and business analysis.

    Each document has at most one score record. Re-running scoring
    updates the existing row rather than creating a new one, mirroring
    `DocumentAnalysis` and `FinancialMetrics`.

    All sub-scores are on a 0-100 scale, where higher is always better
    (including `risk_score`, which represents safety/stability, not
    danger — a high `risk_score` means low risk). A sub-score is `None`
    when there is no underlying data to compute it from, rather than a
    fabricated midpoint value.

    Attributes:
        id: Primary key, a randomly generated UUID.
        document_id: The scored document. Unique, so each document has
            at most one score.
        overall_score: The weighted composite score (0-100), or `None`
            if no sub-scores could be computed at all, or if
            `assessment_status` is `INSUFFICIENT_EVIDENCE` (Step 8: a
            composite is withheld rather than presented as a falsely
            precise number when the underlying evidence is too thin).
        financial_score: Score reflecting revenue/margin/profitability
            strength, or `None` if no financial metrics exist.
        growth_score: Score reflecting growth trajectory, or `None` if
            no growth rate is known.
        risk_score: Score reflecting financial stability (runway, burn,
            profitability) — higher is safer — or `None` if no relevant
            financial metrics exist.
        market_score: Score reflecting the richness/clarity of
            identified market context (industry, customers,
            competitors, revenue streams), or `None` if no business
            analysis exists.
        team_score: Reserved for a future team-strength signal. Always
            `None` in the current data model, since no team-related
            information is captured anywhere in the pipeline yet. Kept
            as a column so it can be populated once a data source for
            it exists, without a schema change.
        confidence_score: Fraction (0.0-1.0) of the five scoring
            dimensions above that could actually be computed.
        reasoning: A human-readable explanation of the score, built
            entirely from the structured data used to compute it. Never
            generated by an LLM.
        created_at: Timezone-aware timestamp when the record was first
            created.
        updated_at: Timezone-aware timestamp when the record was last
            recalculated.
        document: The related `Document`.
        methodology_version: The scoring methodology version that
            produced this record (see `app.core.scoring_config`).
        category_breakdown: Per-category weight/score/contribution
            detail, keyed by dimension (Section 6's transparent
            breakdown) — see `_build_category_breakdown` in
            `investment_scoring_service.py`.
        assessment_status: Whether enough evidence exists to present
            `overall_score` as a single composite number. See
            `AssessmentStatus`.
    """

    __tablename__ = "investment_scores"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    document_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("documents.id", ondelete="CASCADE"),
        unique=True,
        index=True,
        nullable=False,
    )
    overall_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    financial_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    growth_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    risk_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    market_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    team_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    confidence_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    document: Mapped["Document"] = relationship(back_populates="investment_score")
    methodology_version: Mapped[str | None] = mapped_column(String(50), nullable=True)
    category_breakdown: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    assessment_status: Mapped[AssessmentStatus | None] = mapped_column(String(30), nullable=True)

    def __repr__(self) -> str:
        """Return a debug-friendly representation of the score.

        Returns:
            A string identifying the record by document id and overall
            score.
        """
        return (
            f"<InvestmentScore document_id={self.document_id} "
            f"overall_score={self.overall_score}>"
        )