"""Pydantic schemas for the upgraded, evidence-grounded due diligence report."""

import uuid
from enum import Enum

from pydantic import BaseModel, ConfigDict

from app.schemas.chat import ChatSource
from app.schemas.derived_metrics import DerivedMetricRead
from app.schemas.due_diligence import DueDiligenceSection
from app.schemas.validation import ValidationFindingRead


class RecommendationStatus(str, Enum):
    """A structured recommendation status, distinct from free-text reasoning.

    Attributes:
        STRONG_CANDIDATE: Well-supported by available evidence.
        WORTH_EXPLORING: Some positive signals, notable gaps remain.
        NEEDS_MORE_INFO: Insufficient data coverage to form a view.
        CONCERNS_IDENTIFIED: Validation findings or red flags present.
    """

    STRONG_CANDIDATE = "strong_candidate"
    WORTH_EXPLORING = "worth_exploring"
    NEEDS_MORE_INFO = "needs_more_info"
    CONCERNS_IDENTIFIED = "concerns_identified"


class VerifiedFact(BaseModel):
    """A single fact used in the executive summary, grounded in real data.

    Never generated by the LLM directly — built from `FinancialFact`/
    `DerivedMetric` rows, so every figure in the executive view is
    traceable to a stored, citable source.

    Attributes:
        label: A human-readable label (e.g. "2025 Revenue").
        value_display: The formatted value (e.g. "$96.0M").
        source_citation_id: The supporting citation's id, or `None`.
    """

    label: str
    value_display: str
    source_citation_id: str | None = None


class FounderQuestion(BaseModel):
    """A specific question to ask the company, generated deterministically.

    Attributes:
        question: The question text.
        category: Which checklist/validation category prompted it.
        priority: `"high"` for critical findings/missing data, `"medium"` otherwise.
    """

    question: str
    category: str
    priority: str


class DueDiligenceV2Response(BaseModel):
    """Complete, evidence-grounded due diligence report (Section 7).

    Attributes:
        document_id: The analyzed document's id.
        recommendation_status: A structured status, computed from
            validation findings and coverage — not chosen by the LLM.
        executive_summary: The LLM-generated narrative summary (reused
            from the existing `DueDiligenceService`).
        verified_facts: Key facts pulled directly from stored data.
        sections: The original 16 narrative sections (reused as-is).
        red_flags: Validation findings surfaced as report-level red
            flags, most severe first.
        founder_questions: Deterministically generated questions.
        sources: Retrieved document excerpts used as context.
        model_used: The model that generated the narrative sections.
    """

    document_id: uuid.UUID
    recommendation_status: RecommendationStatus
    executive_summary: str
    verified_facts: list[VerifiedFact]
    # Was a bare, untyped `list` here (a stale "avoid circular import"
    # concern -- there is no cycle: due_diligence.py never imports this
    # module). That left every item as a raw dict rather than a
    # DueDiligenceSection whenever this response round-trips through
    # JSON (e.g. the report-export endpoints, which take an
    # already-generated report as their request body) -- server-side
    # construction happened to pass real DueDiligenceSection objects,
    # masking the gap until export tried `.title`/`.content` attribute
    # access on what was, on that path, a plain dict.
    sections: list[DueDiligenceSection]
    red_flags: list[ValidationFindingRead]
    founder_questions: list[FounderQuestion]
    sources: list[ChatSource]
    model_used: str